language: node_js
node_js:
  - "v8.9.4"
before_script:
  - npm install
script:
  - npm test
deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: ci-test
      commit_message: /(\[ci publish .+\])/
